package io.github.znetworkw.znpcservers;

public class UnexpectedCallException extends RuntimeException {
    public UnexpectedCallException(Throwable cause) {
        super(cause);
    }
}
